name: employee-management-api CI/CD 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: 'coverage/lcov.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}
